version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"  # Express API
      - "3001:3001"  # React Frontend
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: